name: CI Pipeline

on:
  push:
    branches: [main]
jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    env:
      CI: true
      build_env: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - run: yarn test
