name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['>=16.0.0']

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Start docker
        run: docker-compose up -d
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn eslint:check
      - name: Prettier
        run: yarn prettier:check
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Test e2e
        run: |
          yarn prisma migrate dev
          yarn prisma db seed
          yarn test:e2e
